---
# Composite Action to run post-test functions for task runner end to end tests

name: 'Post-Test Functions'
description: 'Run post-test functions'
inputs:
  test_type:
    description: 'Test type'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print test summary
      id: print_test_summary
      if: ${{ always() }}
      run: |
        export PYTHONPATH="$PYTHONPATH:."
        python tests/end_to_end/utils/summary_helper.py
        echo "Test summary printed"
      shell: bash

    - name: Create Tar (exclude cert and data folders)
      id: tar_files
      if: ${{ always() }}
      run: |
        tar -cvf result.tar --exclude="cert" --exclude="data" --exclude="__pycache__" $HOME/results
      shell: bash

    - name: Upload Artifacts
      id: upload_artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: ${{ inputs.test_type }}_${{ env.MODEL_NAME }}_python${{ env.PYTHON_VERSION }}_${{ github.run_id }}
        path: result.tar
