name: Windows (latest)

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

env:
  # A workaround for long FQDN names provided by GitHub actions.
  FQDN: "localhost"

jobs:
  pytest-coverage: # from pytest_coverage.yml
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r test-requirements.txt
        pip install .
    - name: Test with pytest and report code coverage
      run: |
        coverage run -m pytest -rA
        coverage report
  
  cli: # from taskrunner.yml
    needs: [pytest-coverage]
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test TaskRunner API
        run: |
          python -m tests.github.test_hello_federation --template keras_cnn_mnist --fed_workspace aggregator --col1 col1 --col2 col2  --rounds-to-train 3 --save-model output_model